In [1]:
pip install numpy

     |████████████████████████████████| 20.0MB 5.3MB/s eta 0:00:01     |████████████████████████▎       | 15.2MB 5.3MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

# 1. Crear numpy array
# 1. Create numpy array

In [15]:
np.array([1, 3, 5])

array([1, 3, 5])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(2, 20, 2, float)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [4]:
np.array([[2, 3], [3, 4], [5, 6]])

array([[2, 3],
       [3, 4],
       [5, 6]])

In [26]:
np.linspace(1, 8, 10)

array([1.        , 1.77777778, 2.55555556, 3.33333333, 4.11111111,
       4.88888889, 5.66666667, 6.44444444, 7.22222222, 8.        ])

In [28]:
np.random.rand(12)

array([0.64002796, 0.8850039 , 0.83143662, 0.93223981, 0.61851006,
       0.04868729, 0.36731488, 0.03245844, 0.05145343, 0.14887028,
       0.59930395, 0.32446777])

In [30]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

# 2. Acceder a los datos
# 2. Data access

In [31]:
x = np.arange(10)

In [35]:
x[0]

0

In [33]:
x[:5]

array([5, 6, 7, 8, 9])

In [36]:
x[5:]

array([5, 6, 7, 8, 9])

In [37]:
x[3:6]

array([3, 4, 5])

In [38]:
x[::2]

array([0, 2, 4, 6, 8])

In [39]:
x[3::2]

array([3, 5, 7, 9])

# 3. 2D y 3D

In [40]:
np.array([[2, 3], [3, 4], [5, 6]])

array([[2, 3],
       [3, 4],
       [5, 6]])

In [5]:
np.array([[[2, 3], [3, 4], [5, 6]], [[2, 3], [3, 4], [5, 6]]])

array([[[2, 3],
        [3, 4],
        [5, 6]],

       [[2, 3],
        [3, 4],
        [5, 6]]])

In [13]:
x = np.array([[[2, 3], [3, 4], [5, 6]], [[2, 3], [3, 4], [5, 6]]])

In [14]:
x[0, 0, 0] 

2